InventorySystem/Inventory/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = "invent"

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),

    # User paths
    path('registration/', views.registration, name='registration'),
    path('login/', auth_views.LoginView.as_view(template_name='inventorySystem/login.html'), name='login'),
    path('account/', auth_views.LoginView.as_view(template_name='inventorySystem/account.html'), name='account'),
    path('logout/', auth_views.LogoutView.as_view(next_page=reverse_lazy('invent:login')), name='logout'),

    #Forgotten password path
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password/password_reset_complete.html'), name='password_reset_complete'),

    # Product paths
    path('list/', views.inventory_list, name='list'),
    path('add/', views.add_product, name='add_new_product'),
    path('update/<int:pk>', views.update_product, name='update_product'),
    path('delete/<int:pk>', views.delete_product, name='delete_product'),
    path('info/<int:pk>', views.product_info, name='product_info'),
]

InventorySystem/InventorySystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Inventory.urls')),
]

InventorySystem/Inventory/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class NewUser(models.Model):
    UserName = models.CharField(max_length=50, unique=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=50)
    confirmPassword = models.CharField(max_length=50)

    REQUIRED_FIELDS = ['username', 'email', 'password']
    USERNAME_FIELD = 'username'


class NewProduct(models.Model):
    itemClass = models.CharField(max_length=50, null=False, blank=False)
    name = models.CharField(max_length=50, null=False, blank=False)
    model = models.CharField(max_length=50, null=False, blank=False)
    quantity = models.PositiveIntegerField(validators=[MaxValueValidator(100), MinValueValidator(1)], blank=False)
    price_per_piece = models.PositiveIntegerField(null=False, blank=False)
    stock_date = models.DateField(auto_now_add=True)
    ready_to_load = models.BooleanField(default=False)

    def __str__(self):
        return self.itemClass + ", " + self.name + ", " + self.model + ", " + str(self.quantity) + ", " + \
               str(self.price_per_piece) + ", " + str(self.stock_date)

InventorySystem/Inventory/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewProduct
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class AddProductsForm(ModelForm):
    class Meta:
        model = NewProduct
        fields = ['itemClass', 'name', 'model', 'quantity', 'price_per_piece', 'ready_to_load']


class UpdateProductForm(ModelForm):
    class Meta:
        model = NewProduct
        fields = ['itemClass', 'name', 'model', 'quantity', 'price_per_piece', 'ready_to_load']

InventorySystem/Inventory/views.py
from .models import NewProduct
from .forms import RegisterForm, AddProductsForm, UpdateProductForm
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm


def registration(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            messages.success(request, "Registration successful.")
            return redirect("invent:login")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = RegisterForm()
    return render(request=request, template_name="inventorySystem/registration.html",
                  context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                return redirect("invent:list")
            else:
                messages.error(request, "Invalid username or password")
        else:
            messages.error(request, "Invalid username or password")
    form = AuthenticationForm()
    return render(request=request, template_name="invent:list", context={"login_form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("invent:login")


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.object.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "Inventory/templates/password/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Dano Tehnics',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="password/password_reset.html",
                  context={"password_reset_form": password_reset_form})


@login_required
def index(request):

    return render(request, 'inventoryTemplates/index.html')


@login_required
def inventory_list(request):
    inventories = NewProduct.objects.all()
    context = {
        "title": "Inventory List",
        "inventories": inventories
    }
    return render(request, 'inventoryTemplates/inventory_list.html', context=context)


@login_required
def add_product(request):
    if request.method == "POST":
        add_form = AddProductsForm(data=request.POST)
        if add_form.is_valid():
            new_inventory = add_form.save(commit=False)
            new_inventory.input = float(add_form.data['price_per_piece']) * float(add_form.data['quantity'])
            new_inventory.save()
            return redirect("/list/")
    else:
        add_form = AddProductsForm()

    return render(request, 'inventoryTemplates/add_product.html', {"form": add_form})


@login_required
def update_product(request, pk):
    inventory = get_object_or_404(NewProduct, pk=pk)
    if request.method == "POST":
        updateForm = UpdateProductForm(data=request.POST)
        if updateForm.is_valid():
            inventory.itemClass = updateForm.data['itemClass']
            inventory.name = updateForm.data['name']
            inventory.model = updateForm.data['model']
            inventory.quantity = updateForm.data['quantity']
            inventory.cost_per_piece = float(updateForm.data['price_per_piece'])
            inventory.save()
            return redirect("/list/")
    else:
        updateForm = UpdateProductForm(instance=inventory)
        context = {
            "form": updateForm
        }
    return render(request, 'inventoryTemplates/update_product.html', {"form": updateForm})


@login_required
def delete_product(request, pk):
    inventory = get_object_or_404(NewProduct, pk=pk)
    inventory.delete()
    return redirect("/list/")


@login_required
def product_info(request, pk):
    inventory = get_object_or_404(NewProduct, pk=pk)
    context = {
        'inventory': inventory,
    }
    return render(request, 'inventoryTemplates/product_info.html', context=context)


def about(request):
    context = {

    }
    return render(request, 'inventoryTemplates/about.html')

InventorySystem/Inventory/templates/inventoryTemplates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css"/>
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Dano Inventory System</title>
    {% endif %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'invent:list' %}">Home</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'invent:add_new_product' %}">Add Product</a>
            </li>
            {% if request.user.is_authenticated %}
            <li>
                <a class="nav-link active" aria-current="page" href="{% url 'invent:logout' %}">Logout</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
<p class="info-tag">About Us:</p>
<p>Dano Technics is engaged in the import, repair and sale of second-hand white/black appliances for the home from the
    Republic of Germany. For 23 years now, we have been taking care of our customers by providing them,
    with the highest quality and reliability appliances.</p>
<p class="services">With us you get:
    <br>-Fast and quality service on time.
    <br>-Free transport and delivery to your door on the product of your choice within the city.
    <br>-Assistance, if needed, for the installation and operation of the device.
    <br>- If you wish, we will pick up and dispose of your old appliance.
    <br>-Support for out-of-warranty devices. In our service.</p>
<p>If you have any further questions, don't hesitate to contact us:
<br>-On location: 124 Third March Blvd., Montana
<br>-On our facebook page: <a href="https://www.facebook.com/profile.php?id=100051914796877">Дано Техникс</a>
<br>-On our phone: 0877077759</p>
</body>
</html>

InventorySystem/Inventory/templates/inventoryTemplates/add_product.html
{% extends "../layout.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-section">
    {{ form.media }}
  <form method="POST"><fieldset>
      <legend class="border-bottom pd-2 mb-4 text-center">Add Product</legend>
      {% csrf_token %}
      <div class="form-group">
        {{ form|crispy }}
      </div>
      <div class="form-group pt-4">
        <button class="btn btn-outline-success" type="submit">Add Product</button>
      </div>
    </fieldset>
  </form>
</div>
{% endblock %}

InventorySystem/Inventory/templates/inventoryTemplates/delete_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

InventorySystem/Inventory/templates/inventoryTemplates/index.html
{% extends "../layout.html" %}
{% block content %}
  <h2>Sup</h2>
{% endblock %}

InventorySystem/Inventory/templates/inventoryTemplates/inventory_list.html
{% extends "../layout.html" %}
{% block content %}

<div class="content-section">
  <table class="table table-striped table-bordered table-hovet">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Item Class</th>
        <th scope="col">Name</th>
        <th scope="col">Model</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price in per piece €</th>
        <th scope="col">Stock Date</th>
        <th scope="col">Ready to load</th>
      </tr>
    </thead>
    <tbody>
      {% for item in inventories %}
        <tr style="cursor: pointer; cursor: hand;" onclick="window.location = `{% url 'invent:product_info' item.id %}`">
          <th scope="row">{{ forloop.counter }}</th>
          <th scope="row">{{ item.itemClass }}</th>
          <th scope="row">{{ item.name }}</th>
          <th scope="row">{{ item.model }}</th>
          <th scope="row">{{ item.quantity }}</th>
          <th scope="row">{{ item.price_per_piece }}</th>
          <th scope="row">{{ item.stock_date }}</th>
          <th scope="row">{{ item.ready_to_load }}</th>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

InventorySystem/Inventory/templates/inventoryTemplates/product_info.html
{% extends "../layout.html" %}
{% block content %}
<div class="content-section">
  <div class="row mx-auto justify-content-center">

    <div class="card m-4" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title text-center">Item Class</h5>
        <div style="font-size: 30px;" class="text-center">
        </div>
        <h3 class="text-center">{{ inventory.itemClass }}</h3>
      </div>
    </div>

    <div class="card m-4" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title text-center">Product Name</h5>
        <div style="font-size: 30px;" class="text-center">
        </div>
        <h3 class="text-center">{{ inventory.name }}</h3>
      </div>
    </div>

    <div class="card m-4" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title text-center">Model</h5>
        <div style="font-size: 30px;" class="text-center">
        </div>
        <h3 class="text-center">{{ inventory.model }}</h3>
      </div>
    </div>

    <div class="card m-4" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title text-center">Quantity</h5>
        <div style="font-size: 30px;" class="text-center">
        </div>
        <h3 class="text-center">{{ inventory.quantity }}</h3>
      </div>
    </div>

    <div class="card m-4" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title text-center">Price in €</h5>
        <div style="font-size: 30px;" class="text-center">
        </div>
        <h3 class="text-center">{{ inventory.price_per_piece }}</h3>
      </div>
    </div>

    <div class="card m-4" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title text-center">Stock Date</h5>
        <div style="font-size: 30px;" class="text-center">
        </div>
        <h3 class="text-center">{{ inventory.stock_date }}</h3>
      </div>
    </div>

    <div class="card m-4" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title text-center">Ready to load</h5>
        <div style="font-size: 30px;" class="text-center">
        </div>
        <h3 class="text-center">{{ inventory.ready_to_load }}</h3>
      </div>
    </div>
    </div>
     <a class="btn btn-success btn-sm mb-3" href="{% url 'invent:update_product' inventory.id %}">Update Product</a>
     <a class="btn btn-danger btn-sm" href="{% url 'invent:delete_product' inventory.id %}">Delete Product</a>

  </div>
</div>
{% endblock %}

InventorySystem/Inventory/templates/inventoryTemplates/update_product.html
{% extends "../layout.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    {{ form.media }}
  <form method="POST"><fieldset>
      <legend class="border-bottom pd-2 mb-4 text-center">Update Product</legend>
      {% csrf_token %}
      <div class="form-group">
        {{ form|crispy }}
      </div>
      <div class="form-group pt-4">
        <button class="btn btn-outline-success" type="submit">Update Product</button>
      </div>
    </fieldset>
  </form>
</div>
{% endblock %}